language: python
dist: xenial
sudo: required
python:
    - "3.6"
    - "3.7"
    - "3.6-dev"
    - "3.7-dev"
install:
    - "make setup"
script:
    - "pip install ."
    - "make test"
matrix:
    allow_failures:
        - python: "3.7"
        - python: "3.6-dev"
        - python: "3.7-dev"
